=== liubao19860416/personal-web-project/personal-web-project/src/main/webapp/myxml/newbook.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bookstore (book+)>
<!ELEMENT book (name,author,price,publisher)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ATTLIST book id CDATA #REQUIRED>
<!ENTITY STR "www.baidu.com">

=== liubao19860416/personal-web-project/personal-web-project/src/main/webapp/myxml/xml_Test_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 <!DOCTYPE bookstore SYSTEM "newbook.dtd">
 -->
<!DOCTYPE bookstore[
<!ELEMENT bookstore (book+)>
<!ELEMENT book (name,author,price,publisher)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ATTLIST book id CDATA #REQUIRED>
<!ENTITY STR "www.baidu.com">
]>

<bookstore>
	<book id="computer1">
		<name>JAVA基础编程</name>
		<author>刘保</author>
		<price>33元</price>
		<publisher>&STR;</publisher>
	</book>
	<book id="computer1">
		<name>C++精讲教程</name>
		<author>王某</author>
		<price>63元</price>
		<publisher>&STR;</publisher>
	</book>
	<book id="forGradute">
		<name>毕业论文指导</name>
		<author>唐彭</author>
		<price>34元</price>
		<publisher>&STR;</publisher>
	</book>
</bookstore>

=== liubao19860416/personal-web-project/personal-web-project/src/main/webapp/myxml/xml_test_dom4j.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bookstore>

<!-- 
 <!DOCTYPE bookstore SYSTEM "newbook.dtd">
 -->
<bookstore>
  <book id="computer1">
    <name>JAVA基础编程</name>
    <author>刘保</author>
    <newPrice>45元</newPrice>
    <publisher>www.baidu.com</publisher>
  </book>
  <book id="computer1">
    <name>C++精讲教程</name>
    <author>王某</author>
    <price>63元</price>
    <publisher>www.baidu.com</publisher>
  </book>
  <book id="forGradute">
    <name>毕业论文指导</name>
    <author>唐彭</author>
    <price>34元</price>
    <publisher>www.baidu.com</publisher>
  </book>
</bookstore>

=== liubao19860416/personal-web-project/personal-web-project/src/main/webapp/myxml/xml_Test_01_coyp.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- 
 <!DOCTYPE bookstore SYSTEM "newbook.dtd">
 --><bookstore>
	<book id="computer1">
		<name>JAVA基础编程</name>
		<author>刘保</author>
		<price>55元</price>
		<publisher>www.baidu.com</publisher>
	</book>
	<book id="computer1">
		<name>C++精讲教程</name>
		<author>王某</author>
		<price>55元</price>
		<publisher>www.baidu.com</publisher>
	</book>
	<book id="forGradute">
		<name>毕业论文指导</name>
		<author>唐彭</author>
		<price>55元</price>
		<publisher>www.baidu.com</publisher>
	</book>
</bookstore>
